package userInterface;

import javafx.scene.control.Button;
/**
 * A class that creates a javaFX Button with a specific index.
 * The index is normally used to reference an element in a list.
 * 
 * <p> <STRONG> Generated by </STRONG> <p>
 * JAXB
 * <p> <STRONG> Developed by </STRONG> <p>
 * Oliver Rushton
 * <p> <STRONG> Tested by </STRONG> <p>
 * Oliver Rushton
 * <p> <STRONG> Developed for </STRONG> <p>
 * BOSS
 * @see Button
 */
public class IndexButton extends Button  {
	
	private int index;
	/**
	 * Creates a javaFX button with the desired name and index.
	 * 
	 * @param name the text to add to the Button
	 * @param index the index of this button.
	 */
	public IndexButton(String name, int index){
		super(name);
		this.index = index;
	}
	/**
	 * Gets the index of the button.
	 * @return the index of the button.
	 */
	public int getIndex() {
		return index;
	}
	/**
	 * Sets the index of the button
	 * @param index the new index of the button.
	 */
	public void setIndex(int index) {
		this.index = index;
	}
	
}
