//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 11:00:44 AM BST 
//


package account;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Each meal will store an integer referencing the index of the meal. '-1' is used for meals that haven't been set.
 * 
 * <p>Java class for dietCalender complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dietCalender"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="monday" type="{http://www.example.org/account}dayDiet"/&gt;
 *         &lt;element name="tuesday" type="{http://www.example.org/account}dayDiet"/&gt;
 *         &lt;element name="wednesday" type="{http://www.example.org/account}dayDiet"/&gt;
 *         &lt;element name="thursday" type="{http://www.example.org/account}dayDiet"/&gt;
 *         &lt;element name="friday" type="{http://www.example.org/account}dayDiet"/&gt;
 *         &lt;element name="saturday" type="{http://www.example.org/account}dayDiet"/&gt;
 *         &lt;element name="sunday" type="{http://www.example.org/account}dayDiet"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dietCalender", propOrder = {
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday"
})
public class DietCalender implements java.io.Serializable {

    @XmlElement(required = true)
    protected DayDiet monday;
    @XmlElement(required = true)
    protected DayDiet tuesday;
    @XmlElement(required = true)
    protected DayDiet wednesday;
    @XmlElement(required = true)
    protected DayDiet thursday;
    @XmlElement(required = true)
    protected DayDiet friday;
    @XmlElement(required = true)
    protected DayDiet saturday;
    @XmlElement(required = true)
    protected DayDiet sunday;

    /**
     * Gets the value of the monday property.
     * 
     * @return
     *     possible object is
     *     {@link DayDiet }
     *     
     */
    public DayDiet getMonday() {
        return monday;
    }

    /**
     * Sets the value of the monday property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayDiet }
     *     
     */
    public void setMonday(DayDiet value) {
        this.monday = value;
    }

    /**
     * Gets the value of the tuesday property.
     * 
     * @return
     *     possible object is
     *     {@link DayDiet }
     *     
     */
    public DayDiet getTuesday() {
        return tuesday;
    }

    /**
     * Sets the value of the tuesday property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayDiet }
     *     
     */
    public void setTuesday(DayDiet value) {
        this.tuesday = value;
    }

    /**
     * Gets the value of the wednesday property.
     * 
     * @return
     *     possible object is
     *     {@link DayDiet }
     *     
     */
    public DayDiet getWednesday() {
        return wednesday;
    }

    /**
     * Sets the value of the wednesday property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayDiet }
     *     
     */
    public void setWednesday(DayDiet value) {
        this.wednesday = value;
    }

    /**
     * Gets the value of the thursday property.
     * 
     * @return
     *     possible object is
     *     {@link DayDiet }
     *     
     */
    public DayDiet getThursday() {
        return thursday;
    }

    /**
     * Sets the value of the thursday property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayDiet }
     *     
     */
    public void setThursday(DayDiet value) {
        this.thursday = value;
    }

    /**
     * Gets the value of the friday property.
     * 
     * @return
     *     possible object is
     *     {@link DayDiet }
     *     
     */
    public DayDiet getFriday() {
        return friday;
    }

    /**
     * Sets the value of the friday property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayDiet }
     *     
     */
    public void setFriday(DayDiet value) {
        this.friday = value;
    }

    /**
     * Gets the value of the saturday property.
     * 
     * @return
     *     possible object is
     *     {@link DayDiet }
     *     
     */
    public DayDiet getSaturday() {
        return saturday;
    }

    /**
     * Sets the value of the saturday property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayDiet }
     *     
     */
    public void setSaturday(DayDiet value) {
        this.saturday = value;
    }

    /**
     * Gets the value of the sunday property.
     * 
     * @return
     *     possible object is
     *     {@link DayDiet }
     *     
     */
    public DayDiet getSunday() {
        return sunday;
    }

    /**
     * Sets the value of the sunday property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayDiet }
     *     
     */
    public void setSunday(DayDiet value) {
        this.sunday = value;
    }

}
