//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.15 at 03:07:05 PM BST 
//


package account;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recentWorkouts complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recentWorkouts"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="workout1" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="workout2" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="workout3" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="workout4" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recentWorkouts")
public class RecentWorkouts implements java.io.Serializable {

    @XmlAttribute(name = "workout1", required = true)
    protected String workout1;
    @XmlAttribute(name = "workout2", required = true)
    protected String workout2;
    @XmlAttribute(name = "workout3", required = true)
    protected String workout3;
    @XmlAttribute(name = "workout4", required = true)
    protected String workout4;

    /**
     * Gets the value of the workout1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkout1() {
        return workout1;
    }

    /**
     * Sets the value of the workout1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkout1(String value) {
        this.workout1 = value;
    }

    /**
     * Gets the value of the workout2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkout2() {
        return workout2;
    }

    /**
     * Sets the value of the workout2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkout2(String value) {
        this.workout2 = value;
    }

    /**
     * Gets the value of the workout3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkout3() {
        return workout3;
    }

    /**
     * Sets the value of the workout3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkout3(String value) {
        this.workout3 = value;
    }

    /**
     * Gets the value of the workout4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkout4() {
        return workout4;
    }

    /**
     * Sets the value of the workout4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkout4(String value) {
        this.workout4 = value;
    }

}
