//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.15 at 03:07:05 PM BST 
//


package account;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "workoutLog")
public class WorkoutEntry implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@XmlAttribute(name = "workoutName", required = true)
    protected String workoutName;
    @XmlAttribute(name = "workoutTime", required = true)
    protected long workoutTime;
    @XmlAttribute(name = "workoutDate", required = true)
    protected String workoutDate;

    /**
     * Gets the value of the workoutName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkoutName() {
        return workoutName;
    }

    /**
     * Sets the value of the workoutName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkoutName(String value) {
        this.workoutName = value;
    }

    /**
     * Gets the value of the workoutTime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getWorkoutTime() {
        return workoutTime;
    }

    /**
     * Sets the value of the workoutTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setWorkoutTime(long value) {
        this.workoutTime = value;
    }
    
    /**
     * Gets the value of the workoutDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkoutDate() {
        return workoutDate;
    }

    /**
     * Sets the value of the workoutDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkoutDate(String value) {
        this.workoutDate = value;
    }

}
