//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.27 at 02:50:18 PM BST 
//


package parser;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import parser.Presentation.Slide.Interactable;
//TODO
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentInfo",
    "defaults",
    "slide"
})
@XmlRootElement(name = "Presentation")
public class Presentation {

    @XmlElement(required = true)
    protected Presentation.DocumentInfo documentInfo;
    @XmlElement(required = true)
    protected Presentation.Defaults defaults;
    protected List<Presentation.Slide> slide;
    @XmlAttribute(name = "workoutDuration")
    protected Integer workoutDuration = 0;

    /**
     * Gets the value of the documentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Presentation.DocumentInfo }
     *     
     */
    public Presentation.DocumentInfo getDocumentInfo() {
        return documentInfo;
    }

    /**
     * Sets the value of the documentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Presentation.DocumentInfo }
     *     
     */
    public void setDocumentInfo(Presentation.DocumentInfo value) {
        this.documentInfo = value;
    }

    /**
     * Gets the value of the defaults property.
     * 
     * @return
     *     possible object is
     *     {@link Presentation.Defaults }
     *     
     */
    public Presentation.Defaults getDefaults() {
        return defaults;
    }

    /**
     * Sets the value of the defaults property.
     * 
     * @param value
     *     allowed object is
     *     {@link Presentation.Defaults }
     *     
     */
    public void setDefaults(Presentation.Defaults value) {
        this.defaults = value;
    }

    /**
     * Gets the value of the slide property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the slide property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSlide().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Presentation.Slide }
     * 
     * 
     */
    public List<Presentation.Slide> getSlide() {
        if (slide == null) {
            slide = new ArrayList<Presentation.Slide>();
        }
        return this.slide;
    }
    
    public void setSlides(List<Presentation.Slide> slides) {
    	this.slide = slides;
    }

    /**
     * Gets the value of the workoutDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWorkoutDuration() {
        return workoutDuration;
    }

    /**
     * Sets the value of the workoutDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWorkoutDuration(Integer value) {
        this.workoutDuration = value;
    }

    //TODO
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "backgroundColour",
        "font",
        "fontsize",
        "fontColour",
        "lineColour",
        "fillColour"
    })
    public static class Defaults {

        @XmlElement(required = true, type = String.class)
        protected String backgroundColour;
        @XmlElement(required = true)
        protected String font;
        protected int fontsize;
        @XmlElement(required = true, type = String.class)
        protected String fontColour = null;
        @XmlElement(required = true, type = String.class)
        protected String lineColour= null;
        @XmlElement(required = true, type = String.class)
        protected String fillColour= null;

        /**
         * Gets the value of the backgroundColour property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBackgroundColour() {
            return backgroundColour;
        }

        /**
         * Sets the value of the backgroundColour property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBackgroundColour(String value) {
            this.backgroundColour = value;
        }

        /**
         * Gets the value of the font property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFont() {
            return font;
        }

        /**
         * Sets the value of the font property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFont(String value) {
            this.font = value;
        }

        /**
         * Gets the value of the fontsize property.
         * 
         */
        public int getFontsize() {
            return fontsize;
        }

        /**
         * Sets the value of the fontsize property.
         * 
         */
        public void setFontsize(int value) {
            this.fontsize = value;
        }

        /**
         * Gets the value of the fontColour property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFontColour() {
            return fontColour;
        }

        /**
         * Sets the value of the fontColour property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFontColour(String value) {
            this.fontColour = value;
        }

        /**
         * Gets the value of the lineColour property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLineColour() {
            return lineColour;
        }

        /**
         * Sets the value of the lineColour property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLineColour(String value) {
            this.lineColour = value;
        }

        /**
         * Gets the value of the fillColour property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFillColour() {
            return fillColour;
        }

        /**
         * Sets the value of the fillColour property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFillColour(String value) {
            this.fillColour = value;
        }

    }


    //TODO
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title",
        "author",
        "version",
        "comment"
    })
    public static class DocumentInfo {

        @XmlElement(name = "Title", required = true)
        protected String title;
        @XmlElement(name = "Author")
        protected String author;
        @XmlElement(name = "Version")
        protected String version;
        @XmlElement(name = "Comment")
        protected String comment;

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the author property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthor() {
            return author;
        }

        /**
         * Sets the value of the author property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthor(String value) {
            this.author = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the comment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComment() {
            return comment;
        }

        /**
         * Sets the value of the comment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComment(String value) {
            this.comment = value;
        }

    }


    //TODO
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "backgroundColour",
        "allContent"
    })
    public static class Slide {

        @XmlElement(type = String.class)
        protected String backgroundColour;
        @XmlElements({
            @XmlElement(name = "text", type = Presentation.Slide.TextType.class),
            @XmlElement(name = "shape", type = Presentation.Slide.ShapeType.class),
            @XmlElement(name = "polygon", type = Presentation.Slide.PolygonType.class),
            @XmlElement(name = "image", type = Presentation.Slide.ImageType.class),
            @XmlElement(name = "video", type = Presentation.Slide.VideoType.class),
            @XmlElement(name = "audio", type = Presentation.Slide.AudioType.class),
            @XmlElement(name = "interactable", type = Presentation.Slide.Interactable.class)
        })
        protected List<Object> allContent;
        @XmlAttribute(name = "slideID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected Integer slideID;
        @XmlAttribute(name = "nextSlide")
        protected Integer nextSlide;
        @XmlAttribute(name = "duration")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected Integer duration = -1;
        @XmlAttribute(name = "exerciseName")
        protected String exerciseName = "none";
        @XmlAttribute(name = "sets")
        protected Integer sets = 0;
        @XmlAttribute(name = "reps")
        protected Integer reps = 0;
        @XmlAttribute(name = "points")
        protected Integer points = 0;
        @XmlAttribute(name = "speed")
        protected Double speed = 0.0;
        @XmlAttribute(name = "strength")
        protected Double strength = 0.0;
        @XmlAttribute(name = "endurance")
        protected Double endurance = 0.0;
        @XmlAttribute(name = "agility")
        protected Double agility = 0.0;
        
        
        
        /**
         * Creates a deep copy of the current Slide
         * 
         * @return clonedSlide
         *     
         */
        public Slide clone() {
        	
        	Slide clonedSlide = new Slide();
        	clonedSlide.setBackgroundColour(this.backgroundColour);
        	clonedSlide.setAllContent(this.cloneAllContent());
        	clonedSlide.setSlideID(this.slideID);
        	clonedSlide.setNextSlide(this.nextSlide);
        	clonedSlide.setDuration(this.duration);
        	clonedSlide.setExerciseName(this.exerciseName);
        	clonedSlide.setSets(this.sets);
        	clonedSlide.setReps(this.reps);
        	clonedSlide.setPoints(this.points);
        	clonedSlide.setSpeed(this.speed);
        	clonedSlide.setStrength(this.strength);
        	clonedSlide.setEndurance(this.endurance);
        	clonedSlide.setAgility(this.agility);
        	
            return clonedSlide;
        }

        
        /**
         * Creates a deep copy of the current Slide's content Array
         * 
         * @return clonedContent
         *     
         */
        private ArrayList<Object> cloneAllContent() {

        	ArrayList<Object> clonedContent = new ArrayList<Object>();
        	for (Object object : allContent) {
        		if (object instanceof Interactable)clonedContent.add(((Interactable) object).clone());
        		if (object instanceof AudioType)clonedContent.add(((AudioType) object).clone());
        		if (object instanceof TextType)clonedContent.add(((TextType) object).clone());
        		if (object instanceof ShapeType)clonedContent.add(((ShapeType) object).clone());
        		if (object instanceof PolygonType)clonedContent.add(((PolygonType) object).clone());
        		if (object instanceof ImageType)clonedContent.add(((ImageType) object).clone());
        		if (object instanceof VideoType)clonedContent.add(((VideoType) object).clone());
			}

            return clonedContent;
		}


		/**
         * Gets the value of the backgroundColour property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBackgroundColour() {
            return backgroundColour;
        }

        /**
         * Sets the value of the backgroundColour property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBackgroundColour(String value) {
            this.backgroundColour = value;
        }

        /**
         * Gets the value of the textAndShapeAndPolygon property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the textAndShapeAndPolygon property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTextAndShapeAndPolygon().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Presentation.Slide.TextType }
         * {@link Presentation.Slide.ShapeType }
         * {@link Presentation.Slide.PolygonType }
         * {@link Presentation.Slide.ImageType }
         * {@link Presentation.Slide.VideoType }
         * {@link Presentation.Slide.AudioType }
         * {@link Presentation.Slide.Interactable }
         * 
         * 
         */
        public List<Object> getAllContent() {
            if (allContent == null) {
            	allContent = new ArrayList<Object>();
            }
            return this.allContent;
        }
        
        public void setAllContent(ArrayList<Object> contentList) {
            this.allContent = contentList;
        }

        /**
         * Gets the value of the slideID property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public Integer getSlideID() {
            return slideID;
        }

        /**
         * Sets the value of the slideID property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSlideID(Integer value) {
            this.slideID = value;
        }

        /**
         * Gets the value of the nextSlide property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public Integer getNextSlide() {
            return nextSlide;
        }

        /**
         * Sets the value of the nextSlide property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNextSlide(Integer value) {
            this.nextSlide = value;
        }

        /**
         * Gets the value of the duration property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public Integer getDuration() {
            return duration;
        }

        /**
         * Sets the value of the duration property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDuration(Integer value) {
            this.duration = value;
        }

        /**
         * Gets the value of the exerciseName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExerciseName() {
            return exerciseName;
        }

        /**
         * Sets the value of the exerciseName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExerciseName(String value) {
            this.exerciseName = value;
        }

        /**
         * Gets the value of the sets property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSets() {
            return sets;
        }

        /**
         * Sets the value of the sets property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSets(Integer value) {
            this.sets = value;
        }

        /**
         * Gets the value of the reps property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getReps() {
            return reps;
        }

        /**
         * Sets the value of the reps property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setReps(Integer value) {
            this.reps = value;
        }

        /**
         * Gets the value of the points property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPoints() {
            return points;
        }

        /**
         * Sets the value of the points property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPoints(Integer value) {
            this.points = value;
        }

        /**
         * Gets the value of the speed property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getSpeed() {
            return speed;
        }

        /**
         * Sets the value of the speed property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setSpeed(Double value) {
            this.speed = value;
        }

        /**
         * Gets the value of the strength property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getStrength() {
            return strength;
        }

        /**
         * Sets the value of the strength property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setStrength(Double value) {
            this.strength = value;
        }

        /**
         * Gets the value of the endurance property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getEndurance() {
            return endurance;
        }

        /**
         * Sets the value of the endurance property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setEndurance(Double value) {
            this.endurance = value;
        }

        /**
         * Gets the value of the agility property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getAgility() {
            return agility;
        }

        /**
         * Sets the value of the agility property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setAgility(Double value) {
            this.agility = value;
        }


        //TODO
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AudioType {

            @XmlAttribute(name = "starttime", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected Integer starttime = null;
            @XmlAttribute(name = "duration", required = true)
            protected Integer duration = null;
            @XmlAttribute(name = "sourceFile", required = true)
            protected String sourceFile;
            @XmlAttribute(name = "loop", required = true)
            protected boolean loop;
            
            
            /**
             * Creates a deep copy of the current AudioType
             * 
             * @return clonedAudio
             *     
             */
            public AudioType clone() {
            	
            	AudioType clonedAudio = new AudioType();
            	clonedAudio.setStarttime(this.starttime);
            	clonedAudio.setDuration(this.duration);
            	clonedAudio.setSourceFile(this.sourceFile);
            	clonedAudio.setLoop(this.loop);
            	
                return clonedAudio;
            }
            
            /**
             * Gets the value of the starttime property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public Integer getStarttime() {
                return starttime;
            }

            /**
             * Sets the value of the starttime property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setStarttime(Integer value) {
                this.starttime = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             */
            public Integer getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             */
            public void setDuration(Integer value) {
                this.duration = value;
            }

            /**
             * Gets the value of the sourceFile property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSourceFile() {
                return sourceFile;
            }

            /**
             * Sets the value of the sourceFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSourceFile(String value) {
                this.sourceFile = value;
            }

            /**
             * Gets the value of the loop property.
             * 
             */
            public boolean isLoop() {
                return loop;
            }

            /**
             * Sets the value of the loop property.
             * 
             */
            public void setLoop(boolean value) {
                this.loop = value;
            }

        }


        //TODO
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ImageType {

            @XmlAttribute(name = "sourceFile", required = true)
            protected String sourceFile;
            @XmlAttribute(name = "starttime", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected Integer starttime = null;
            @XmlAttribute(name = "duration", required = true)
            protected Integer duration = null;
            @XmlAttribute(name = "xstart", required = true)
            protected Float xstart = null;
            @XmlAttribute(name = "ystart", required = true)
            protected Float ystart = null;
            @XmlAttribute(name = "width", required = true)
            protected Float width = null;
            @XmlAttribute(name = "height", required = true)
            protected Float height = null;
            
            /**
             * Creates a deep copy of the current ImageType
             * 
             * @return clonedImage
             *     
             */
            public ImageType clone() {
            	
            	ImageType clonedImage = new ImageType();
            	clonedImage.setStarttime(this.starttime);
            	clonedImage.setDuration(this.duration);
            	clonedImage.setSourceFile(this.sourceFile);
            	clonedImage.setXstart(this.xstart);
            	clonedImage.setYstart(this.ystart);
            	clonedImage.setWidth(this.width);
            	clonedImage.setHeight(this.height);
            	
                return clonedImage;
            }
            
            /**
             * Gets the value of the sourceFile property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSourceFile() {
                return sourceFile;
            }

            /**
             * Sets the value of the sourceFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSourceFile(String value) {
                this.sourceFile = value;
            }

            /**
             * Gets the value of the starttime property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public Integer getStarttime() {
                return starttime;
            }

            /**
             * Sets the value of the starttime property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setStarttime(Integer value) {
                this.starttime = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             */
            public Integer getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             */
            public void setDuration(Integer value) {
                this.duration = value;
            }

            /**
             * Gets the value of the xstart property.
             * 
             */
            public Float getXstart() {
                return xstart;
            }

            /**
             * Sets the value of the xstart property.
             * 
             */
            public void setXstart(Float value) {
                this.xstart = value;
            }

            /**
             * Gets the value of the ystart property.
             * 
             */
            public Float getYstart() {
                return ystart;
            }

            /**
             * Sets the value of the ystart property.
             * 
             */
            public void setYstart(Float value) {
                this.ystart = value;
            }

            /**
             * Gets the value of the width property.
             * 
             */
            public Float getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             */
            public void setWidth(Float value) {
                this.width = value;
            }

            /**
             * Gets the value of the height property.
             * 
             */
            public Float getHeight() {
                return height;
            }

            /**
             * Sets the value of the height property.
             * 
             */
            public void setHeight(Float value) {
                this.height = value;
            }

        }


        //TODO
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "text",
            "shape",
            "polygon",
            "image",
            "video"
        })
        public static class Interactable {

            protected Presentation.Slide.TextType text;
            protected Presentation.Slide.ShapeType shape;
            protected Presentation.Slide.PolygonType polygon;
            protected Presentation.Slide.ImageType image;
            protected Presentation.Slide.VideoType video;
            @XmlAttribute(name = "targetSlide", required = true)
            protected Integer targetSlide = null;
            
            /**
             * Creates a deep copy of the current Interactaable
             * 
             * @return clonedImage
             *     
             */
            public Interactable clone() {
            	
            	Interactable clonedInteract = new Interactable();
            	if(this.targetSlide != null)clonedInteract.setTargetSlide(this.targetSlide);
            	if(this.text != null)clonedInteract.setText(this.text.clone());
            	if(this.shape != null)clonedInteract.setShape(this.shape.clone());
            	if(this.polygon != null)clonedInteract.setPolygon(this.polygon.clone());
            	if(this.image != null)clonedInteract.setImage(this.image.clone());
            	if(this.video != null)clonedInteract.setVideo(this.video.clone());
            	
                return clonedInteract;
            }
            
            /**
             * Gets the value of the text property.
             * 
             * @return
             *     possible object is
             *     {@link Presentation.Slide.Interactable.TextType }
             *     
             */
            public Presentation.Slide.TextType getText() {
                return text;
            }

            /**
             * Sets the value of the text property.
             * 
             * @param value
             *     allowed object is
             *     {@link Presentation.Slide.Interactable.TextType }
             *     
             */
            public void setText(Presentation.Slide.TextType value) {
                this.text = value;
            }

            /**
             * Gets the value of the shape property.
             * 
             * @return
             *     possible object is
             *     {@link Presentation.Slide.Interactable.ShapeType }
             *     
             */
            public Presentation.Slide.ShapeType getShape() {
                return shape;
            }

            /**
             * Sets the value of the shape property.
             * 
             * @param value
             *     allowed object is
             *     {@link Presentation.Slide.Interactable.ShapeType }
             *     
             */
            public void setShape(Presentation.Slide.ShapeType value) {
                this.shape = value;
            }

            /**
             * Gets the value of the polygon property.
             * 
             * @return
             *     possible object is
             *     {@link Presentation.Slide.Interactable.PolygonType }
             *     
             */
            public Presentation.Slide.PolygonType getPolygon() {
                return polygon;
            }

            /**
             * Sets the value of the polygon property.
             * 
             * @param value
             *     allowed object is
             *     {@link Presentation.Slide.Interactable.PolygonType }
             *     
             */
            public void setPolygon(Presentation.Slide.PolygonType value) {
                this.polygon = value;
            }

            /**
             * Gets the value of the image property.
             * 
             * @return
             *     possible object is
             *     {@link Presentation.Slide.ImageType }
             *     
             */
            public Presentation.Slide.ImageType getImage() {
                return image;
            }

            /**
             * Sets the value of the image property.
             * 
             * @param value
             *     allowed object is
             *     {@link Presentation.Slide.ImageType }
             *     
             */
            public void setImage(Presentation.Slide.ImageType value) {
                this.image = value;
            }

            /**
             * Gets the value of the video property.
             * 
             * @return
             *     possible object is
             *     {@link Presentation.Slide.Interactable.VideoType }
             *     
             */
            public Presentation.Slide.VideoType getVideo() {
                return video;
            }

            /**
             * Sets the value of the video property.
             * 
             * @param value
             *     allowed object is
             *     {@link Presentation.Slide.Interactable.VideoType }
             *     
             */
            public void setVideo(Presentation.Slide.VideoType value) {
                this.video = value;
            }

            /**
             * Gets the value of the targetSlide property.
             * 
             */
            public Integer getTargetSlide() {
                return targetSlide;
            }

            /**
             * Sets the value of the targetSlide property.
             * 
             */
            public void setTargetSlide(Integer value) {
                this.targetSlide = value;
            }

        }


        //TODO
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "shading"
        })
        public static class PolygonType {

            protected Presentation.Slide.ShadingType shading;
            @XmlAttribute(name = "starttime", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected Integer starttime = null;
            @XmlAttribute(name = "sourceFile", required = true)
            protected String sourceFile;
            @XmlAttribute(name = "duration", required = true)
            protected Integer duration = null;
            @XmlAttribute(name = "lineColour")
            protected String lineColour = null;
            @XmlAttribute(name = "fillColour")
            protected String fillColour = null;
            
            /**
             * Creates a deep copy of the current PolygonType
             * 
             * @return clonedPoly
             *     
             */
            public PolygonType clone() {
            	
            	PolygonType clonedPoly = new PolygonType();
            	clonedPoly.setShading(this.shading.clone());
            	clonedPoly.setStarttime(this.starttime);
            	clonedPoly.setSourceFile(this.sourceFile);
            	clonedPoly.setDuration(this.duration);
            	clonedPoly.setLineColour(this.lineColour);
            	clonedPoly.setFillColour(this.fillColour);
            	
                return clonedPoly;
            }
            
            /**
             * Gets the value of the shading property.
             * 
             * @return
             *     possible object is
             *     {@link Presentation.Slide.PolygonType.ShadingType }
             *     
             */
            public Presentation.Slide.ShadingType getShading() {
                return shading;
            }

            /**
             * Sets the value of the shading property.
             * 
             * @param value
             *     allowed object is
             *     {@link Presentation.Slide.PolygonType.ShadingType }
             *     
             */
            public void setShading(Presentation.Slide.ShadingType value) {
                this.shading = value;
            }

            /**
             * Gets the value of the starttime property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public Integer getStarttime() {
                return starttime;
            }

            /**
             * Sets the value of the starttime property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setStarttime(Integer value) {
                this.starttime = value;
            }

            /**
             * Gets the value of the sourceFile property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSourceFile() {
                return sourceFile;
            }

            /**
             * Sets the value of the sourceFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSourceFile(String value) {
                this.sourceFile = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             */
            public Integer getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             */
            public void setDuration(Integer value) {
                this.duration = value;
            }

            /**
             * Gets the value of the lineColour property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLineColour() {
                return lineColour;
            }

            /**
             * Sets the value of the lineColour property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLineColour(String value) {
                this.lineColour = value;
            }

            /**
             * Gets the value of the fillColour property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFillColour() {
                return fillColour;
            }

            /**
             * Sets the value of the fillColour property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFillColour(String value) {
                this.fillColour = value;
            }

        }


        //TODO
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "shading"
        })
        public static class ShapeType {

            protected Presentation.Slide.ShadingType shading;
            @XmlAttribute(name = "starttime", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected Integer starttime = null;
            @XmlAttribute(name = "duration", required = true)
            protected Integer duration = null;
            @XmlAttribute(name = "xstart", required = true)
            protected Float xstart = null;
            @XmlAttribute(name = "ystart", required = true)
            protected Float ystart = null;
            @XmlAttribute(name = "type", required = true)
            protected String type;
            @XmlAttribute(name = "width", required = true)
            protected Float width = null;
            @XmlAttribute(name = "height", required = true)
            protected Float height = null;
            @XmlAttribute(name = "lineColour")
            protected String lineColour = null;
            @XmlAttribute(name = "fillColour")
            protected String fillColour = null;
            
            /**
             * Creates a deep copy of the current ShapeType
             * 
             * @return clonedShape
             *     
             */
            public ShapeType clone() {
            	
            	ShapeType clonedShape = new ShapeType();
            	clonedShape.setShading(this.shading.clone());
            	clonedShape.setStarttime(this.starttime);
            	clonedShape.setDuration(this.duration);
            	clonedShape.setLineColour(this.lineColour);
            	clonedShape.setFillColour(this.fillColour);
            	clonedShape.setXstart(this.xstart);
            	clonedShape.setYstart(this.ystart);
            	clonedShape.setWidth(this.width);
            	clonedShape.setHeight(this.height);
            	
                return clonedShape;
            }
            
            /**
             * Gets the value of the shading property.
             * 
             * @return
             *     possible object is
             *     {@link Presentation.Slide.ShapeType.ShadingType }
             *     
             */
            public Presentation.Slide.ShadingType getShading() {
                return shading;
            }

            /**
             * Sets the value of the shading property.
             * 
             * @param value
             *     allowed object is
             *     {@link Presentation.Slide.ShapeType.ShadingType }
             *     
             */
            public void setShading(Presentation.Slide.ShadingType value) {
                this.shading = value;
            }

            /**
             * Gets the value of the starttime property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public Integer getStarttime() {
                return starttime;
            }

            /**
             * Sets the value of the starttime property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setStarttime(Integer value) {
                this.starttime = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             */
            public Integer getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             */
            public void setDuration(Integer value) {
                this.duration = value;
            }

            /**
             * Gets the value of the xstart property.
             * 
             */
            public Float getXstart() {
                return xstart;
            }

            /**
             * Sets the value of the xstart property.
             * 
             */
            public void setXstart(Float value) {
                this.xstart = value;
            }

            /**
             * Gets the value of the ystart property.
             * 
             */
            public Float getYstart() {
                return ystart;
            }

            /**
             * Sets the value of the ystart property.
             * 
             */
            public void setYstart(Float value) {
                this.ystart = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the width property.
             * 
             */
            public Float getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             */
            public void setWidth(Float value) {
                this.width = value;
            }

            /**
             * Gets the value of the height property.
             * 
             */
            public Float getHeight() {
                return height;
            }

            /**
             * Sets the value of the height property.
             * 
             */
            public void setHeight(Float value) {
                this.height = value;
            }

            /**
             * Gets the value of the lineColour property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLineColour() {
                return lineColour;
            }

            /**
             * Sets the value of the lineColour property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLineColour(String value) {
                this.lineColour = value;
            }

            /**
             * Gets the value of the fillColour property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFillColour() {
                return fillColour;
            }

            /**
             * Sets the value of the fillColour property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFillColour(String value) {
                this.fillColour = value;
            }

        }
        
        //TODO
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class TextType {

            @XmlValue
            protected String content;
            @XmlAttribute(name = "starttime", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected Integer starttime = null;
            @XmlAttribute(name = "duration", required = true)
            protected Integer duration = null;
            @XmlAttribute(name = "xstart", required = true)
            protected Float xstart = null;
            @XmlAttribute(name = "ystart", required = true)
            protected Float ystart = null;
            @XmlAttribute(name = "font")
            protected String font;
            @XmlAttribute(name = "fontsize")
            protected Integer fontsize;
            @XmlAttribute(name = "fontcolour")
            protected String fontcolour = null;
            @XmlAttribute(name = "width")
            protected Float width;
            @XmlAttribute(name = "height")
            protected Float height;
            
            /**
             * Creates a deep copy of the current TextType
             * 
             * @return clonedText
             *     
             */
            public TextType clone() {
            	
            	TextType clonedText = new TextType();
            	clonedText.setText(this.content);
            	clonedText.setStarttime(this.starttime);
            	clonedText.setDuration(this.duration);
            	clonedText.setXstart(this.xstart);
            	clonedText.setYstart(this.ystart);
            	clonedText.setWidth(this.width);
            	clonedText.setHeight(this.height);
            	clonedText.setFont(this.font);
            	clonedText.setFontsize(this.fontsize);
            	clonedText.setFontcolour(this.fontcolour);
            	
                return clonedText;
            }

            /**
             * 
             * 												Text to be displayed
             * 												(mixed type means the
             * 												content can be a string
             * 												with b and i tags
             * 												embedded)
             * 											Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link String }
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * 
             * 
             */
            public String getText() {
                return this.content;
            }
            
            /**
             * Sets the value of the content property.
             * 
             * @param text
             *     
             */
            public void setText(String text) {
                this.content = text;
            }

            /**
             * Gets the value of the starttime property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public Integer getStarttime() {
                return starttime;
            }

            /**
             * Sets the value of the starttime property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setStarttime(Integer value) {
                this.starttime = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             */
            public Integer getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             */
            public void setDuration(Integer value) {
                this.duration = value;
            }

            /**
             * Gets the value of the xstart property.
             * 
             */
            public Float getXstart() {
                return xstart;
            }

            /**
             * Sets the value of the xstart property.
             * 
             */
            public void setXstart(Float value) {
                this.xstart = value;
            }

            /**
             * Gets the value of the ystart property.
             * 
             */
            public Float getYstart() {
                return ystart;
            }

            /**
             * Sets the value of the ystart property.
             * 
             */
            public void setYstart(Float value) {
                this.ystart = value;
            }

            /**
             * Gets the value of the font property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFont() {
                return font;
            }

            /**
             * Sets the value of the font property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFont(String value) {
                this.font = value;
            }

            /**
             * Gets the value of the fontsize property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getFontsize() {
                return fontsize;
            }

            /**
             * Sets the value of the fontsize property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setFontsize(Integer value) {
                this.fontsize = value;
            }

            /**
             * Gets the value of the fontcolour property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFontcolour() {
                return fontcolour;
            }

            /**
             * Sets the value of the fontcolour property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFontcolour(String value) {
                this.fontcolour = value;
            }

            /**
             * Gets the value of the width property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public Float getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWidth(Float value) {
                this.width = value;
            }

            /**
             * Gets the value of the height property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public Float getHeight() {
                return height;
            }

            /**
             * Sets the value of the height property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHeight(Float value) {
                this.height = value;
            }

        }


        //TODO
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class VideoType {

            @XmlAttribute(name = "starttime", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected Integer starttime = null;
            @XmlAttribute(name = "duration", required = true)
            protected Integer duration = null;
            @XmlAttribute(name = "xstart", required = true)
            protected Float xstart = null;
            @XmlAttribute(name = "ystart", required = true)
            protected Float ystart = null;
            @XmlAttribute(name = "sourceFile", required = true)
            protected String sourceFile;
            @XmlAttribute(name = "loop", required = true)
            protected boolean loop;
            @XmlAttribute(name = "width")
            protected Double width = null;
            @XmlAttribute(name = "height")
            protected Double height = null;
            
            /**
             * Creates a deep copy of the current VideoType
             * 
             * @return clonedVideo
             *     
             */
            public VideoType clone() {
            	
            	VideoType clonedVideo = new VideoType();
            	clonedVideo.setStarttime(this.starttime);
            	clonedVideo.setDuration(this.duration);
            	clonedVideo.setXstart(this.xstart);
            	clonedVideo.setYstart(this.ystart);
            	clonedVideo.setWidth(this.width);
            	clonedVideo.setHeight(this.height);
            	clonedVideo.setSourceFile(this.sourceFile);
            	clonedVideo.setLoop(this.loop);
            	
                return clonedVideo;
            }
            
            /**
             * Gets the value of the starttime property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public Integer getStarttime() {
                return starttime;
            }

            /**
             * Sets the value of the starttime property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setStarttime(Integer value) {
                this.starttime = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             */
            public Integer getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             */
            public void setDuration(Integer value) {
                this.duration = value;
            }

            /**
             * Gets the value of the xstart property.
             * 
             */
            public Float getXstart() {
                return xstart;
            }

            /**
             * Sets the value of the xstart property.
             * 
             */
            public void setXstart(Float value) {
                this.xstart = value;
            }

            /**
             * Gets the value of the ystart property.
             * 
             */
            public Float getYstart() {
                return ystart;
            }

            /**
             * Sets the value of the ystart property.
             * 
             */
            public void setYstart(Float value) {
                this.ystart = value;
            }

            /**
             * Gets the value of the sourceFile property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSourceFile() {
                return sourceFile;
            }

            /**
             * Sets the value of the sourceFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSourceFile(String value) {
                this.sourceFile = value;
            }

            /**
             * Gets the value of the loop property.
             * 
             */
            public boolean isLoop() {
                return loop;
            }

            /**
             * Sets the value of the loop property.
             * 
             */
            public void setLoop(boolean value) {
                this.loop = value;
            }

            /**
             * Gets the value of the width property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setWidth(Double value) {
                this.width = value;
            }

            /**
             * Gets the value of the height property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getHeight() {
                return height;
            }

            /**
             * Sets the value of the height property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setHeight(Double value) {
                this.height = value;
            }

        }
        
        //TODO
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ShadingType {

            @XmlAttribute(name = "x1", required = true)
            protected Float x1 = null;
            @XmlAttribute(name = "y1", required = true)
            protected Float y1 = null;
            @XmlAttribute(name = "colour1", required = true)
            protected String colour1;
            @XmlAttribute(name = "x2", required = true)
            protected Float x2 = null;
            @XmlAttribute(name = "y2", required = true)
            protected Float y2 = null;
            @XmlAttribute(name = "colour2", required = true)
            protected String colour2;
            
            /**
             * Creates a deep copy of the current ShadingType
             * 
             * @return clonedShading
             *     
             */
            public ShadingType clone() {
            	
            	ShadingType clonedShading = new ShadingType();
            	clonedShading.setX1(this.x1);
            	clonedShading.setY1(this.y1);
            	clonedShading.setColour1(this.colour1);
            	clonedShading.setX1(this.x1);
            	clonedShading.setY1(this.y1);
            	clonedShading.setColour1(this.colour1);
            	
                return clonedShading;
            }
            
            /**
             * Gets the value of the x1 property.
             * 
             */
            public Float getX1() {
                return x1;
            }

            /**
             * Sets the value of the x1 property.
             * 
             */
            public void setX1(Float value) {
                this.x1 = value;
            }

            /**
             * Gets the value of the y1 property.
             * 
             */
            public Float getY1() {
                return y1;
            }

            /**
             * Sets the value of the y1 property.
             * 
             */
            public void setY1(Float value) {
                this.y1 = value;
            }

            /**
             * Gets the value of the colour1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColour1() {
                return colour1;
            }

            /**
             * Sets the value of the colour1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColour1(String value) {
                this.colour1 = value;
            }

            /**
             * Gets the value of the x2 property.
             * 
             */
            public Float getX2() {
                return x2;
            }

            /**
             * Sets the value of the x2 property.
             * 
             */
            public void setX2(Float value) {
                this.x2 = value;
            }

            /**
             * Gets the value of the y2 property.
             * 
             */
            public Float getY2() {
                return y2;
            }

            /**
             * Sets the value of the y2 property.
             * 
             */
            public void setY2(Float value) {
                this.y2 = value;
            }

            /**
             * Gets the value of the colour2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColour2() {
                return colour2;
            }

            /**
             * Sets the value of the colour2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColour2(String value) {
                this.colour2 = value;
            }

        }

    }

}
