//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.25 at 01:28:05 PM GMT 
//


package parser;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * A 'regular' shape element
 *
 * <p>Java class for ShapeType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ShapeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="shading" type="{SwengPWS}ShadingType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="starttime" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="xstart" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float"&gt;
 *             &lt;minInclusive value="0"/&gt;
 *             &lt;maxInclusive value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ystart" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float"&gt;
 *             &lt;minInclusive value="0"/&gt;
 *             &lt;maxInclusive value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="width" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float"&gt;
 *             &lt;minInclusive value="0"/&gt;
 *             &lt;maxInclusive value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="height" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float"&gt;
 *             &lt;minInclusive value="0"/&gt;
 *             &lt;maxInclusive value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="lineColour"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary"&gt;
 *             &lt;pattern value="\w{6}"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="fillColour"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary"&gt;
 *             &lt;pattern value="\w{6}"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShapeType", propOrder = {
        "shading"
})
public class ShapeType {

    protected ShadingType shading;
    @XmlAttribute(name = "starttime", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer starttime;
    @XmlAttribute(name = "duration", required = true)
    protected Integer duration;
    @XmlAttribute(name = "xstart", required = true)
    protected Float xstart = null;
    @XmlAttribute(name = "ystart", required = true)
    protected Float ystart = null;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "width", required = true)
    protected Float width = null;
    @XmlAttribute(name = "height", required = true)
    protected Float height = null;
    @XmlAttribute(name = "lineColour")
    protected String lineColour = null;
    @XmlAttribute(name = "fillColour")
    protected String fillColour = null;

    /**
     * Gets the value of the shading property.
     *
     * @return
     *     possible object is
     *     {@link ShadingType }
     *
     */
    public ShadingType getShading() {
        return shading;
    }

    /**
     * Sets the value of the shading property.
     *
     * @param value
     *     allowed object is
     *     {@link ShadingType }
     *
     */
    public void setShading(ShadingType value) {
        this.shading = value;
    }

    /**
     * Gets the value of the starttime property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public Integer getStarttime() {
        return starttime;
    }

    /**
     * Sets the value of the starttime property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setStarttime(Integer value) {
        this.starttime = value;
    }

    /**
     * Gets the value of the duration property.
     *
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     *
     */
    public void setDuration(Integer value) {
        this.duration = value;
    }

    /**
     * Gets the value of the xstart property.
     *
     */
    public Float getXstart() {
        return xstart;
    }

    /**
     * Sets the value of the xstart property.
     *
     */
    public void setXstart(Float value) {
        this.xstart = value;
    }

    /**
     * Gets the value of the ystart property.
     *
     */
    public Float getYstart() {
        return ystart;
    }

    /**
     * Sets the value of the ystart property.
     *
     */
    public void setYstart(Float value) {
        this.ystart = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the width property.
     *
     */
    public Float getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     *
     */
    public void setWidth(Float value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     *
     */
    public Float getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     *
     */
    public void setHeight(Float value) {
        this.height = value;
    }

    /**
     * Gets the value of the lineColour property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLineColour() {
        return lineColour;
    }

    /**
     * Sets the value of the lineColour property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLineColour(String value) {
        this.lineColour = value;
    }

    /**
     * Gets the value of the fillColour property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFillColour() {
        return fillColour;
    }

    /**
     * Sets the value of the fillColour property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFillColour(String value) {
        this.fillColour = value;
    }

}
