//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.25 at 01:28:05 PM GMT 
//


package parser;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * A custom shape, defined by a sequence of points.
 * 
 * <p>Java class for PolygonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolygonType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="shading" type="{SwengPWS}ShadingType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="starttime" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="sourceFile" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="lineColour"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary"&gt;
 *             &lt;pattern value="\w{6}"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="fillColour"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary"&gt;
 *             &lt;pattern value="\w{6}"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolygonType", propOrder = {
    "shading"
})
public class PolygonType {

    protected ShadingType shading;
    @XmlAttribute(name = "starttime", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer starttime = null;
    @XmlAttribute(name = "sourceFile", required = true)
    protected String sourceFile;
    @XmlAttribute(name = "duration", required = true)
    protected Integer duration = null;
    @XmlAttribute(name = "lineColour")
    protected String lineColour = null;
    @XmlAttribute(name = "fillColour")
    protected String fillColour = null;

    /**
     * Gets the value of the shading property.
     * 
     * @return
     *     possible object is
     *     {@link ShadingType }
     *     
     */
    public ShadingType getShading() {
        return shading;
    }

    /**
     * Sets the value of the shading property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShadingType }
     *     
     */
    public void setShading(ShadingType value) {
        this.shading = value;
    }

    /**
     * Gets the value of the starttime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public Integer getStarttime() {
        return starttime;
    }

    /**
     * Sets the value of the starttime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStarttime(Integer value) {
        this.starttime = value;
    }

    /**
     * Gets the value of the sourceFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceFile() {
        return sourceFile;
    }

    /**
     * Sets the value of the sourceFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceFile(String value) {
        this.sourceFile = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     */
    public void setDuration(Integer value) {
        this.duration = value;
    }

    /**
     * Gets the value of the lineColour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineColour() {
        return lineColour;
    }

    /**
     * Sets the value of the lineColour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineColour(String value) {
        this.lineColour = value;
    }

    /**
     * Gets the value of the fillColour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillColour() {
        return fillColour;
    }

    /**
     * Sets the value of the fillColour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillColour(String value) {
        this.fillColour = value;
    }

}
