//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.15 at 01:29:45 PM BST 
//


package diet;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A class used to store the list of ingredients and instructions for a particular 
 * recipe. Also stores a path to the recipe image and the recipe name, type and index. 
 * This class was originally generated from the account xsd file via JAXB, but has since been manually 
 * edited and corrected.
 * 
 * <p> <STRONG> Developed by </STRONG> <p>
 * Oliver Rushton
 * <p> <STRONG> Tested by </STRONG> <p>
 * Oliver Rushton
 * <p> <STRONG> Developed for </STRONG> <p>
 * BOSS
 * @author Oliver Rushton
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "instructions",
    "ingredients"
})
@XmlRootElement(name = "Recipe")
public class Recipe {

    @XmlElement(required = true)
    protected List<Instruction> instructions;
    @XmlElement(required = true)
    protected List<Ingredient> ingredients;
    @XmlAttribute(name = "mealName", required = true)
    protected String mealName;
    @XmlAttribute(name = "imageFile", required = true)
    protected String imageFile;
    @XmlAttribute(name = "index", required = true)
    protected int index;
    @XmlAttribute(name = "mealType", required = true)
    protected int mealType;

    /**
     * Gets the value of the instructions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instructions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstructions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Instruction }
     * 
     * 
     */
    public List<Instruction> getInstructions() {
        if (instructions == null) {
            instructions = new ArrayList<Instruction>();
        }
        return this.instructions;
    }

    /**
     * Gets the value of the ingredients property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ingredients property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIngredients().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ingredient }
     * 
     * 
     */
    public List<Ingredient> getIngredients() {
        if (ingredients == null) {
            ingredients = new ArrayList<Ingredient>();
        }
        return this.ingredients;
    }

    /**
     * Gets the value of the mealName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMealName() {
        return mealName;
    }

    /**
     * Sets the value of the mealName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMealName(String value) {
        this.mealName = value;
    }

    /**
     * Gets the value of the imageFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageFile() {
        return imageFile;
    }

    /**
     * Sets the value of the imageFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageFile(String value) {
        this.imageFile = value;
    }

    /**
     * Gets the value of the index property.
     * 
     */
    public int getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     */
    public void setIndex(int value) {
        this.index = value;
    }

    /**
     * Gets the value of the mealType property.
     * 
     */
    public int getMealType() {
        return mealType;
    }

    /**
     * Sets the value of the mealType property.
     * 
     */
    public void setMealType(int value) {
        this.mealType = value;
    }

}
