//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.15 at 01:29:45 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/recipeStructure", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package diet;
