//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.15 at 03:07:05 PM BST 
//


package account;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "characterAttributes")
public class CharacterAttributes implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@XmlAttribute(name = "strength", required = true)
    protected int strength;
    @XmlAttribute(name = "speed", required = true)
    protected int speed;
    @XmlAttribute(name = "endurance", required = true)
    protected int endurance;
    @XmlAttribute(name = "agility", required = true)
    protected int agility;
    @XmlAttribute(name = "baseAttack", required = true)
    protected double baseAttack;
    @XmlAttribute(name = "baseDefense", required = true)
    protected double baseDefense;
    @XmlAttribute(name = "health", required = true)
    protected int health;
    @XmlAttribute(name = "equippedItem", required = true)
    protected int equippedItem;
    @XmlAttribute(name = "move1", required = true)
    protected int move1;
    @XmlAttribute(name = "move2", required = true)
    protected int move2;
    @XmlAttribute(name = "move3", required = true)
    protected int move3;
    @XmlAttribute(name = "move4", required = true)
    protected int move4;
    @XmlElement(required = true)
    protected CharacterParts characterSource;
    

    /**
     * Gets the value of the strength property.
     * 
     */
    public int getStrength() {
        return strength;
    }

    /**
     * Sets the value of the strength property.
     * 
     */
    public void setStrength(int value) {
        this.strength = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     */
    public int getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     */
    public void setSpeed(int value) {
        this.speed = value;
    }

    /**
     * Gets the value of the endurance property.
     * 
     */
    public int getEndurance() {
        return endurance;
    }

    /**
     * Sets the value of the endurance property.
     * 
     */
    public void setEndurance(int value) {
        this.endurance = value;
    }

    /**
     * Gets the value of the agility property.
     * 
     */
    public int getAgility() {
        return agility;
    }

    /**
     * Sets the value of the agility property.
     * 
     */
    public void setAgility(int value) {
        this.agility = value;
    }
    
    /**
     * Gets the value of the baseAttack property.
     * 
     */
    public double getBaseAttack() {
    	return baseAttack;
    }
    
    /**
     * Sets the value of the baseAttack property.
     * 
     */
    public void setBaseAttack(double value) {
        this.baseAttack = value;
    }
    
    /**
     * Gets the value of the baseDefense property.
     * 
     */
    public double getBaseDefense() {
    	return baseDefense;
    }
    
    /**
     * Sets the value of the baseDefense property.
     * 
     */
    public void setBaseDefense(double value) {
        this.baseDefense = value;
    }
    
    /**
     * Gets the value of the health property.
     * 
     */
    public int getHealth() {
    	return health;
    }
    
    /**
     * Sets the value of the health property.
     * 
     */
    public void setHealth(int value) {
        this.health = value;
    }
    
    /**
     * Gets the value of the equippedItem property.
     * 
     */
    public int getEquippedItem() {
    	return equippedItem;
    }
    
    /**
     * Sets the value of the equippedItem property.
     * 
     */
    public void setEquippedItem(int value) {
        this.equippedItem = value;
    }
    
    /**
     * Gets the value of the move1 property.
     * 
     */
    public int getMove1() {
    	return move1;
    }
    
    /**
     * Sets the value of the move1 property.
     * 
     */
    public void setMove1(int value) {
        this.move1 = value;
    }
    
    /**
     * Gets the value of the move2 property.
     * 
     */
    public int getMove2() {
    	return move2;
    }
    
    /**
     * Sets the value of the move2 property.
     * 
     */
    public void setMove2(int value) {
        this.move2 = value;
    }
    
    /**
     * Gets the value of the move3 property.
     * 
     */
    public int getMove3() {
    	return move3;
    }
    
    /**
     * Sets the value of the move3 property.
     * 
     */
    public void setMove3(int value) {
        this.move3 = value;
    }
    
    /**
     * Gets the value of the move4 property.
     * 
     */
    public int getMove4() {
    	return move4;
    }
    
    /**
     * Sets the value of the move4 property.
     * 
     */
    public void setMove4(int value) {
        this.move4 = value;
    }
    
    /**
     * Gets the value of the characterSource property.
     * 
     * @return
     *     possible object is
     *     {@link CharacterParts }
     *     
     */
    public CharacterParts getCharacterSource() {
        return characterSource;
    }

    /**
     * Sets the value of the characterSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharacterParts }
     *     
     */
    public void setCharacterSource(CharacterParts value) {
        this.characterSource = value;
    }

}
