//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.18 at 08:36:15 PM BST
//


package account;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * A class used to store all the associated attributes of an 
 * <tt>CharacterPart</tt> for an {@link Account} loaded in by
 * the JAXB Marshaller from an xml file generated by the account.xsd. 
 * This Class was generated by JAXB and then manually modified.
 * 
 * <p> <STRONG> Generated by </STRONG> <p>
 * JAXB
 * <p> <STRONG> Developed by </STRONG> <p>
 * Oliver Rushton
 * <p> <STRONG> Tested by </STRONG> <p>
 * Oliver Rushton
 * <p> <STRONG> Developed for </STRONG> <p>
 * BOSS
 * @author Oliver Rushton
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "characterParts")
public class CharacterParts implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@XmlAttribute(name = "bodySource", required = true)
	protected String bodySource;
	@XmlAttribute(name = "hairSource", required = true)
	protected String hairSource;
	@XmlAttribute(name = "eyesSource", required = true)
	protected String eyesSource;

	/**
	 * Gets the value of the bodySource property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getBodySource() {
		return bodySource;
	}

	/**
	 * Sets the value of the bodySource property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setBodySource(String value) {
		this.bodySource = value;
	}

	/**
	 * Gets the value of the hairSource property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getHairSource() {
		return hairSource;
	}

	/**
	 * Sets the value of the hairSource property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setHairSource(String value) {
		this.hairSource = value;
	}

	/**
	 * Gets the value of the eyesSource property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getEyesSource() {
		return eyesSource;
	}

	/**
	 * Sets the value of the eyesSource property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setEyesSource(String value) {
		this.eyesSource = value;
	}

}
