//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.15 at 03:07:05 PM BST 
//


package account;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "characterParts")
public class CharacterParts implements java.io.Serializable {
	
	@XmlAttribute(name = "bodySource", required = true)
	protected String bodySource;
	@XmlAttribute(name = "hairSource", required = true)
	protected String hairSource;
	@XmlAttribute(name = "eyesSource", required = true)
	protected String eyesSource;
	
	/**
	 *  Gets the value of the bodySource attribute
	 */
	public String getBodySource() {
		return bodySource;
	}
	/**
	 *  Sets the value of the bodySource attribute
	 */
	public void setBodySource(String bodySource) {
		this.bodySource = bodySource;
	}
	/**
	 *  Gets the value of the hairSource attribute
	 */
	public String getHairSource() {
		return hairSource;
	}
	/**
	 *  Sets the value of the hairSource attribute
	 */
	public void setHairSource(String hairSource) {
		this.hairSource = hairSource;
	}
	/**
	 *  Gets the value of the eyesSource attribute
	 */
	public String getEyesSource() {
		return eyesSource;
	}
	/**
	 *  Sets the value of the eyesSource attribute
	 */
	public void setEyesSource(String eyesSource) {
		this.eyesSource = eyesSource;
	}

}
