//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.05.15 at 03:07:05 PM BST
//


package account;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * A class used to store the the index of the recipe xml's for each meal: 
 * Breakfast, Lunch and Dinner. This class was originally generated 
 * from the account xsd file via JAXB, but has since been manually 
 * edited and corrected.
 * <p>
 * This class has to be serializable as the object will be sent over socket communications.
 * 
 * <p> <STRONG> Developed by </STRONG> <p>
 * Oliver Rushton
 * <p> <STRONG> Tested by </STRONG> <p>
 * Oliver Rushton
 * <p> <STRONG> Developed for </STRONG> <p>
 * BOSS
 * @author Oliver Rushton
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dayDiet")
public class DayDiet implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    @XmlAttribute(name = "breakfast", required = true)
    protected int breakfast;
    @XmlAttribute(name = "lunch", required = true)
    protected int lunch;
    @XmlAttribute(name = "dinner", required = true)
    protected int dinner;

    /**
     * Gets the value of the breakfast property.
     *
     */
    public int getBreakfast() {
        return breakfast;
    }

    /**
     * Sets the value of the breakfast property.
     *
     */
    public void setBreakfast(int value) {
        this.breakfast = value;
    }

    /**
     * Gets the value of the lunch property.
     *
     */
    public int getLunch() {
        return lunch;
    }

    /**
     * Sets the value of the lunch property.
     *
     */
    public void setLunch(int value) {
        this.lunch = value;
    }

    /**
     * Gets the value of the dinner property.
     *
     */
    public int getDinner() {
        return dinner;
    }

    /**
     * Sets the value of the dinner property.
     *
     */
    public void setDinner(int value) {
        this.dinner = value;
    }

}
