//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.05.15 at 03:07:05 PM BST
//


package account;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * A class used to store the 4 most recent workout xml names.
 * <p>
 * <STRONG>WARNING:</STRONG> This class's functionality has been replaced 
 * by the History field in the {@link Account} class.
 * <p>
 * This class has to be serializable as the object will be sent over socket communications.
 * 
 * <p> <STRONG> Developed by </STRONG> <p>
 * Oliver Rushton
 * <p> <STRONG> Tested by </STRONG> <p>
 * Oliver Rushton
 * <p> <STRONG> Developed for </STRONG> <p>
 * BOSS
 * @author Oliver Rushton
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recentWorkouts")
public class RecentWorkouts implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@XmlAttribute(name = "workout1", required = true)
    protected String workout1;
    @XmlAttribute(name = "workout2", required = true)
    protected String workout2;
    @XmlAttribute(name = "workout3", required = true)
    protected String workout3;
    @XmlAttribute(name = "workout4", required = true)
    protected String workout4;

    /**
     * Gets the value of the workout1 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWorkout1() {
        return workout1;
    }

    /**
     * Sets the value of the workout1 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWorkout1(String value) {
        this.workout1 = value;
    }

    /**
     * Gets the value of the workout2 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWorkout2() {
        return workout2;
    }

    /**
     * Sets the value of the workout2 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWorkout2(String value) {
        this.workout2 = value;
    }

    /**
     * Gets the value of the workout3 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWorkout3() {
        return workout3;
    }

    /**
     * Sets the value of the workout3 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWorkout3(String value) {
        this.workout3 = value;
    }

    /**
     * Gets the value of the workout4 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWorkout4() {
        return workout4;
    }

    /**
     * Sets the value of the workout4 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWorkout4(String value) {
        this.workout4 = value;
    }

}
